Net Position needs to be a float and not decimal
  File "C:\Users\Peter\git\ByteBucks\TradingBot\OrderBook.py", line 129, in on_message
    self.net_position = self.net_position - Float(message['size'])
NameError: name 'Float' is not defined